management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics

  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

  metrics:
    tags:
      application: monitoringtest

spring:
  application:
    name: application
  cloud:
    vault:
      token: ${vaultToken}
      host: ${vaultAddr}
      scheme: http
      kv:
        enabled: true
  config:
    import: vault://

server:
  forward-headers-strategy: framework
